import { StepsData } from "components/atoms/steps";
import { TEXT_CONSTANTS } from "presentation/texts-reservoir";

const AUTH_PREMIER_ADMIN_SIGN_UP_STEPS_CONFIG: StepsData = [
  { title: TEXT_CONSTANTS.PREMIER_ADMIN_SIGN_UP.STEPS.LOG_IN },
  { title: TEXT_CONSTANTS.PREMIER_ADMIN_SIGN_UP.STEPS.CHANGE_PASSWORD },
  { title: TEXT_CONSTANTS.PREMIER_ADMIN_SIGN_UP.STEPS.INVITE_TEAMMATES },
  { title: TEXT_CONSTANTS.PREMIER_ADMIN_SIGN_UP.STEPS.GET_STARTED },
];

export { AUTH_PREMIER_ADMIN_SIGN_UP_STEPS_CONFIG };
