export const sampleCSVData = [
  {
    poNumber: "0037-8874295-3806",
    poDate: "7/10/2022",
    releaseNumber: "004010",
    retailersPo: "0037-8874295-3806",
    shipDates: "7/15/2022 - 7/16/2022",
    recordType: "H",
    carrier: "USE VRS",
    poPurpose: "original_00",
    poType: "stand_alone_order_SA",
    contractNumber: "D",
    vendorNumber: "1981199",
    paymentTerms: "2",
    paymentTermsDiscDaysDue: "65",
    frtTerms: "defined_by_buyer_and_seller_DF",
    buyingPartyName: "TARGET DC                     3806",
    buyingPartyLocation: "3806",
    buyingPartyAddress1: "2702 SUMMIT AVE",
    buyingPartyCity: "RIALTO",
    buyingPartyState: "CA",
    buyingPartyZip: "92377",
    buyingPartyCountry: "US",
    poTotalAmount: 3823.92,
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 1,
    recordType: "D",
    qtyOrdered: "192",
    unitPrice: "1.49",
    retailPrice: "3.39",
    unitOfMeasure: "each_EA",
    upcEan: "810046632956",
    buyersCatalogOrStockKeepingNumber: "037080079",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "6",
    productItemDescription: "Joon X Moon",
    vendorStyle: "jxm0170",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 2,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "2.34",
    retailPrice: "4.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632604",
    buyersCatalogOrStockKeepingNumber: "037080244",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "CHAM04",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 3,
    recordType: "D",
    qtyOrdered: "168",
    unitPrice: "2.34",
    retailPrice: "4.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632680",
    buyersCatalogOrStockKeepingNumber: "037080281",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "6",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0156",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 4,
    recordType: "D",
    qtyOrdered: "312",
    unitPrice: "2.34",
    retailPrice: "4.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632581",
    buyersCatalogOrStockKeepingNumber: "037080346",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "6",
    productItemDescription: "Joon X Moon",
    vendorStyle: "MNCH01",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 5,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "3.96",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632932",
    buyersCatalogOrStockKeepingNumber: "037082706",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0169",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 6,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "3.96",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632901",
    buyersCatalogOrStockKeepingNumber: "037083221",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0167",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 7,
    recordType: "D",
    qtyOrdered: "36",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632192",
    buyersCatalogOrStockKeepingNumber: "037083671",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0165",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 8,
    recordType: "D",
    qtyOrdered: "36",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632215",
    buyersCatalogOrStockKeepingNumber: "037083711",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0164",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 9,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "4.22",
    retailPrice: "10.69",
    unitOfMeasure: "each_EA",
    upcEan: "850008905650",
    buyersCatalogOrStockKeepingNumber: "037084520",
    numberOfInnerPacks: "12",
    productItemDescription: "Joon XMoon",
    vendorStyle: "JXM0120",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 10,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632208",
    buyersCatalogOrStockKeepingNumber: "037085323",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "CCNU01",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 11,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "4.22",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905117",
    buyersCatalogOrStockKeepingNumber: "037086262",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0008",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 12,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "3.96",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632925",
    buyersCatalogOrStockKeepingNumber: "037087496",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0168",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 13,
    recordType: "D",
    qtyOrdered: "36",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905155",
    buyersCatalogOrStockKeepingNumber: "037088061",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0012",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 14,
    recordType: "D",
    qtyOrdered: "12",
    unitPrice: "2.34",
    retailPrice: "4.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632628",
    buyersCatalogOrStockKeepingNumber: "037088424",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "WHTE10",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 15,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "2.34",
    retailPrice: "4.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632635",
    buyersCatalogOrStockKeepingNumber: "037088500",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "CCNU04",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 16,
    recordType: "D",
    qtyOrdered: "36",
    unitPrice: "4.22",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905124",
    buyersCatalogOrStockKeepingNumber: "037088523",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0009",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 17,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905162",
    buyersCatalogOrStockKeepingNumber: "037088564",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0013",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 18,
    recordType: "D",
    qtyOrdered: "36",
    unitPrice: "2.34",
    retailPrice: "4.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632611",
    buyersCatalogOrStockKeepingNumber: "037088697",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "LAVE06",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 19,
    recordType: "D",
    qtyOrdered: "72",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905148",
    buyersCatalogOrStockKeepingNumber: "037089015",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0011",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 20,
    recordType: "D",
    qtyOrdered: "60",
    unitPrice: "4.22",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905100",
    buyersCatalogOrStockKeepingNumber: "037089218",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0007",
  },
  {
    poNumber: "0037-8874295-3806",
    poLineNumber: 21,
    recordType: "D",
    qtyOrdered: "48",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632260",
    buyersCatalogOrStockKeepingNumber: "037089697",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "WHTE08",
  },
  {
    poNumber: "0037-7126510-0587",
    poDate: "5/29/2022",
    releaseNumber: "004010",
    retailersPo: "0037-7126510-0587",
    shipDates: "6/3/2022 - 6/4/2022",
    recordType: "H",
    carrier: "USE VRS",
    poPurpose: "original_00",
    poType: "stand_alone_order_SA",
    contractNumber: "D",
    vendorNumber: "1981199",
    paymentTerms: "2",
    paymentTermsDiscDaysDue: "65",
    frtTerms: "defined_by_buyer_and_seller_DF",
    buyingPartyName: "TARGET DC                     0587",
    buyingPartyLocation: "0587",
    buyingPartyAddress1: "12905 EAST L AVENUE",
    buyingPartyCity: "GALESBURG",
    buyingPartyState: "MI",
    buyingPartyZip: "49053",
    buyingPartyCountry: "US",
    poTotalAmount: 1952.64,
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 1,
    recordType: "D",
    qtyOrdered: "144",
    unitPrice: "1.49",
    retailPrice: "2.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632956",
    buyersCatalogOrStockKeepingNumber: "037080079",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "6",
    productItemDescription: "Joon X Moon",
    vendorStyle: "jxm0170",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 2,
    recordType: "D",
    qtyOrdered: "12",
    unitPrice: "2.34",
    retailPrice: "4.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632604",
    buyersCatalogOrStockKeepingNumber: "037080244",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "CHAM04",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 3,
    recordType: "D",
    qtyOrdered: "120",
    unitPrice: "2.34",
    retailPrice: "4.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632680",
    buyersCatalogOrStockKeepingNumber: "037080281",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "6",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0156",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 4,
    recordType: "D",
    qtyOrdered: "240",
    unitPrice: "2.34",
    retailPrice: "4.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632581",
    buyersCatalogOrStockKeepingNumber: "037080346",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "6",
    productItemDescription: "Joon X Moon",
    vendorStyle: "MNCH01",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 5,
    recordType: "D",
    qtyOrdered: "12",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632192",
    buyersCatalogOrStockKeepingNumber: "037083671",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0165",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 6,
    recordType: "D",
    qtyOrdered: "12",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632215",
    buyersCatalogOrStockKeepingNumber: "037083711",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0164",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 7,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "4.22",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905650",
    buyersCatalogOrStockKeepingNumber: "037084520",
    numberOfInnerPacks: "12",
    productItemDescription: "Joon XMoon",
    vendorStyle: "JXM0120",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 8,
    recordType: "D",
    qtyOrdered: "12",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632208",
    buyersCatalogOrStockKeepingNumber: "037085323",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "CCNU01",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 9,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "4.22",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905117",
    buyersCatalogOrStockKeepingNumber: "037086262",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0008",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 10,
    recordType: "D",
    qtyOrdered: "12",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905155",
    buyersCatalogOrStockKeepingNumber: "037088061",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0012",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 11,
    recordType: "D",
    qtyOrdered: "12",
    unitPrice: "2.34",
    retailPrice: "4.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632635",
    buyersCatalogOrStockKeepingNumber: "037088500",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "CCNU04",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 12,
    recordType: "D",
    qtyOrdered: "12",
    unitPrice: "4.22",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905124",
    buyersCatalogOrStockKeepingNumber: "037088523",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0009",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 13,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905162",
    buyersCatalogOrStockKeepingNumber: "037088564",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0013",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 14,
    recordType: "D",
    qtyOrdered: "12",
    unitPrice: "2.34",
    retailPrice: "4.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632611",
    buyersCatalogOrStockKeepingNumber: "037088697",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "LAVE06",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 15,
    recordType: "D",
    qtyOrdered: "24",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905148",
    buyersCatalogOrStockKeepingNumber: "037089015",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0011",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 16,
    recordType: "D",
    qtyOrdered: "12",
    unitPrice: "4.22",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "850008905100",
    buyersCatalogOrStockKeepingNumber: "037089218",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "JXM0007",
  },
  {
    poNumber: "0037-7126510-0587",
    poLineNumber: 17,
    recordType: "D",
    qtyOrdered: "12",
    unitPrice: "4.7",
    retailPrice: "9.99",
    unitOfMeasure: "each_EA",
    upcEan: "810046632260",
    buyersCatalogOrStockKeepingNumber: "037089697",
    numberOfInnerPacks: "4",
    numberOfPcsPerInnerPack: "3",
    productItemDescription: "Joon X Moon",
    vendorStyle: "WHTE08",
  },
];

export const blankObject = {
  poNumber: "",
  releaseNumber: "",
  poDate: "",
  deptNumber: "",
  retailersPo: "",
  requestedDeliveryDate: "",
  deliveryDates: "",
  shipDates: "",
  cancelDate: "",
  carrier: "",
  carrierDetails: "",
  shipToLocation: "",
  poLineNumber: "",
  qtyOrdered: "",
  unitOfMeasure: "",
  unitPrice: "",
  buyersCatalogOrStockKeepingNumber: "",
  upcEan: "",
  vendorStyle: "",
  retailPrice: "",
  productItemDescription: "",
  color: "",
  size: "",
  packSize: "",
  packSizeUom: "",
  numberOfInnerPacks: "",
  numberOfPcsPerInnerPack: "",
  storeNumber: "",
  qtyPerStoreNumber: "",
  recordType: "",
  poPurpose: "",
  poType: "",
  contractNumber: "",
  currency: "",
  shipStatus: "",
  letterOfCredit: "",
  vendorNumber: "",
  divisionNumber: "",
  custAcctNumber: "",
  customerOrderNumber: "",
  promoNumber: "",
  ticketDescription: "",
  otherInfoNumbers: "",
  frtTerms: "",
  carrierServiceLevel: "",
  paymentTerms: "",
  paymentTermsDiscDueDate: "",
  paymentTermsDiscDaysDue: "",
  paymentTermsNetDueDate: "",
  paymentTermsNetDays: "",
  paymentTermsDiscAmt: "",
  paymentTermsDesc: "",
  contactPhone: "",
  contactFax: "",
  contactEmail: "",
  allowChargeType: "",
  allowChargeService: "",
  allowChargeAmt: "",
  allowCharge: "",
  allowChargeRate: "",
  allowChargeQty: "",
  allowChargeDesc: "",
  shipToName: "",
  shipToAddress1: "",
  shipToAddress2: "",
  shipToCity: "",
  shipToState: "",
  shipToZip: "",
  shipToCountry: "",
  shipToContact: "",
  billToName: "",
  billToAddress1: "",
  billToAddress2: "",
  billToCity: "",
  billToState: "",
  billToZip: "",
  billToCountry: "",
  billToContact: "",
  buyingPartyName: "",
  buyingPartyLocation: "",
  buyingPartyAddress1: "",
  buyingPartyAddress2: "",
  buyingPartyCity: "",
  buyingPartyState: "",
  buyingPartyZip: "",
  buyingPartyCountry: "",
  buyingPartyContact: "",
  ultimateLocation: "",
  notesComments: "",
  shipToAdditionalName: "",
  shipToAdditionalName2: "",
  billToAdditionalName: "",
  billToAdditionalName2: "",
  buyerAdditionalName: "",
  buyerAdditionalName2: "",
  gtin: "",
  poTotalAmount: "",
  poTotalWeight: "",
  poTotalUom: "",
  shippingAccountNumber: "",
  markForName: "",
  markForAddress1: "",
  markForAddress2: "",
  markForCity: "",
  markForState: "",
  markForPostal: "",
  markForCountry: "",
  shippingContainerCode: "",
  nationalDrugCode: "",
  expirationDate: "",
  dist: "",
  scheduledQuantity: "",
  scheduledQtyUom: "",
  requiredByDate: "",
  mustArriveBy: "",
  entireShipment: "",
  agreementNumber: "",
  additionalVendorPartNumber: "",
  buyerPartNumber: "",
  carrierDetailsSpecialHandling: "",
};
export const poCsvConfig = [
  {
    key: "poNumber",
    label: "PO Number",
    hidden: false,
  },
  {
    key: "poDate",
    label: "PO Date",
    hidden: false,
  },
  {
    key: "poTotalAmount",
    label: "PO Total Amount",
    hidden: false,
  },
  {
    key: "poTotalWeight",
    label: "PO Total Weight ",
    hidden: false,
  },
  {
    key: "poTotalUom",
    label: "PO Total UOM ",
    hidden: false,
  },
  {
    key: "deptNumber",
    label: "Dept Number",
    hidden: false,
  },
  {
    key: "retailersPo",
    label: "Retailers PO",
    hidden: false,
  },
  {
    key: "buyingPartyName",
    label: "Buying Party Name",
    hidden: false,
  },
  {
    key: "buyingPartyLocation",
    label: "Buying Party Location",
    hidden: false,
  },
  {
    key: "buyingPartyAddress1",
    label: "Buying Party Address 1",
    hidden: false,
  },
  {
    key: "buyingPartyAddress2",
    label: "Buying Party Address 2",
    hidden: false,
  },
  {
    key: "buyingPartyCity",
    label: "Buying Party City",
    hidden: false,
  },
  {
    key: "buyingPartyState",
    label: "Buying Party State",
    hidden: false,
  },
  {
    key: "buyingPartyZip",
    label: "Buying Party Zip",
    hidden: false,
  },
  {
    key: "buyingPartyCountry",
    label: "Buying Party Country",
    hidden: false,
  },
  {
    key: "buyingPartyContact",
    label: "Buying Party Contact",
    hidden: false,
  },
  {
    key: "poLineNumber",
    label: "PO Line Number",
    hidden: false,
  },
  {
    key: "qtyOrdered",
    label: "Qty Ordered",
    hidden: false,
  },
  {
    key: "unitOfMeasure",
    label: "Unit of Measure",
    hidden: false,
  },
  {
    key: "unitPrice",
    label: "Unit Price",
    hidden: false,
  },
  {
    key: "buyersCatalogOrStockKeepingNumber",
    label: "Buyers Catalog or Stock Keeping Number",
    hidden: false,
  },
  {
    key: "upcEan",
    label: "UPC/EAN",
    hidden: false,
  },
  {
    key: "vendorStyle",
    label: "Vendor Style",
    hidden: false,
  },
  {
    key: "retailPrice",
    label: "Retail Price",
    hidden: false,
  },
  {
    key: "productItemDescription",
    label: "Product/Item Description",
    hidden: false,
  },
  {
    key: "color",
    label: "Color",
    hidden: false,
  },
  {
    key: "size",
    label: "Size",
    hidden: false,
  },
  {
    key: "packSize",
    label: "Pack Size",
    hidden: false,
  },
  {
    key: "packSizeUom",
    label: "Pack Size UOM",
    hidden: false,
  },
  {
    key: "numberOfInnerPacks",
    label: "Number of Inner Packs",
    hidden: false,
  },
  {
    key: "numberOfPcsPerInnerPack",
    label: "Number of Pcs per Inner Pack",
    hidden: false,
  },
  {
    key: "storeNumber",
    label: "Store Number",
    hidden: false,
  },
  {
    key: "qtyPerStoreNumber",
    label: "Qty per Store Number",
    hidden: false,
  },
  {
    key: "recordType",
    label: "Record Type",
    hidden: false,
  },
  {
    key: "poPurpose",
    label: "PO purpose",
    hidden: false,
  },
  {
    key: "poType",
    label: "PO Type",
    hidden: false,
  },
  {
    key: "contractNumber",
    label: "Contract Number",
    hidden: false,
  },
  {
    key: "requestedDeliveryDate",
    label: "Requested Delivery Date",
    hidden: false,
  },
  {
    key: "deliveryDates",
    label: "Delivery Dates",
    hidden: false,
  },
  {
    key: "shipDates",
    label: "Ship Dates",
    hidden: false,
  },
  {
    key: "cancelDate",
    label: "Cancel Date",
    hidden: false,
  },
  {
    key: "carrier",
    label: "Carrier",
    hidden: false,
  },
  {
    key: "carrierDetails",
    label: "Carrier Details",
    hidden: false,
  },
  {
    key: "shipToLocation",
    label: "Ship To Location",
    hidden: false,
  },
  {
    key: "currency",
    label: "Currency",
    hidden: false,
  },
  {
    key: "shipStatus",
    label: "Ship Status",
    hidden: false,
  },
  {
    key: "letterOfCredit",
    label: "Letter of Credit",
    hidden: false,
  },
  {
    key: "vendorNumber",
    label: "Vendor Number",
    hidden: false,
  },
  {
    key: "divisionNumber",
    label: "Division Number",
    hidden: false,
  },
  {
    key: "custAcctNumber",
    label: "Cust Acct Number",
    hidden: false,
  },
  {
    key: "customerOrderNumber",
    label: "Customer Order Number",
    hidden: false,
  },
  {
    key: "promoNumber",
    label: "Promo Number",
    hidden: false,
  },
  {
    key: "ticketDescription",
    label: "Ticket Description",
    hidden: false,
  },
  {
    key: "otherInfoNumbers",
    label: "Other Info / Numbers",
    hidden: false,
  },
  {
    key: "frtTerms",
    label: "Frt Terms",
    hidden: false,
  },
  {
    key: "carrierServiceLevel",
    label: "Carrier Service Level",
    hidden: false,
  },
  {
    key: "paymentTerms",
    label: "Payment Terms %",
    hidden: false,
  },
  {
    key: "paymentTermsDiscDueDate",
    label: "Payment Terms Disc Due Date",
    hidden: false,
  },
  {
    key: "paymentTermsDiscDaysDue",
    label: "Payment Terms Disc Days Due",
    hidden: false,
  },
  {
    key: "paymentTermsNetDueDate",
    label: "Payment Terms Net Due Date",
    hidden: false,
  },
  {
    key: "paymentTermsNetDays",
    label: "Payment Terms Net Days",
    hidden: false,
  },
  {
    key: "paymentTermsDiscAmt",
    label: "Payment Terms Disc Amt",
    hidden: false,
  },
  {
    key: "paymentTermsDesc",
    label: "Payment Terms Desc",
    hidden: false,
  },
  {
    key: "contactPhone",
    label: "Contact Phone",
    hidden: false,
  },
  {
    key: "contactFax",
    label: "Contact Fax",
    hidden: false,
  },
  {
    key: "contactEmail",
    label: "Contact Email",
    hidden: false,
  },
  {
    key: "allowChargeType",
    label: "Allow/Charge Type",
    hidden: false,
  },
  {
    key: "allowChargeService",
    label: "Allow/Charge Service",
    hidden: false,
  },
  {
    key: "allowChargeAmt",
    label: "Allow/Charge Amt",
    hidden: false,
  },
  {
    key: "allowCharge",
    label: "Allow/Charge %",
    hidden: false,
  },
  {
    key: "allowChargeRate",
    label: "Allow/Charge Rate",
    hidden: false,
  },
  {
    key: "allowChargeQty",
    label: "Allow/Charge Qty",
    hidden: false,
  },
  {
    key: "allowChargeDesc",
    label: "Allow/Charge Desc",
    hidden: false,
  },
  {
    key: "shipToName",
    label: "Ship To Name",
    hidden: false,
  },
  {
    key: "shipToAddress1",
    label: "Ship To Address 1",
    hidden: false,
  },
  {
    key: "shipToAddress2",
    label: "Ship To Address 2",
    hidden: false,
  },
  {
    key: "shipToCity",
    label: "Ship To City",
    hidden: false,
  },
  {
    key: "shipToState",
    label: "Ship To State",
    hidden: false,
  },
  {
    key: "shipToZip",
    label: "Ship to Zip",
    hidden: false,
  },
  {
    key: "shipToCountry",
    label: "Ship To Country",
    hidden: false,
  },
  {
    key: "shipToContact",
    label: "Ship To Contact",
    hidden: false,
  },
  {
    key: "billToName",
    label: "Bill To Name",
    hidden: false,
  },
  {
    key: "billToAddress1",
    label: "Bill To Address 1",
    hidden: false,
  },
  {
    key: "billToAddress2",
    label: "Bill To Address 2",
    hidden: false,
  },
  {
    key: "billToCity",
    label: "Bill To City",
    hidden: false,
  },
  {
    key: "billToState",
    label: "Bill To State",
    hidden: false,
  },
  {
    key: "billToZip",
    label: "Bill To Zip",
    hidden: false,
  },
  {
    key: "billToCountry",
    label: "Bill To Country",
    hidden: false,
  },
  {
    key: "billToContact",
    label: "Bill To Contact",
    hidden: false,
  },
  {
    key: "ultimateLocation",
    label: "Ultimate Location",
    hidden: false,
  },
  {
    key: "notesComments",
    label: "Notes/Comments",
    hidden: false,
  },
  {
    key: "shipToAdditionalName",
    label: "Ship To Additional Name",
    hidden: false,
  },
  {
    key: "shipToAdditionalName2",
    label: "Ship To Additional Name 2",
    hidden: false,
  },
  {
    key: "billToAdditionalName",
    label: "Bill To Additional Name",
    hidden: false,
  },
  {
    key: "billToAdditionalName2",
    label: "Bill To Additional Name 2",
    hidden: false,
  },
  {
    key: "buyerAdditionalName",
    label: "Buyer Additional Name",
    hidden: false,
  },
  {
    key: "buyerAdditionalName2",
    label: "Buyer Additional Name 2",
    hidden: false,
  },
  {
    key: "gtin",
    label: "GTIN",
    hidden: false,
  },
  {
    key: "shippingAccountNumber",
    label: "Shipping account number",
    hidden: false,
  },
  {
    key: "markForName",
    label: "Mark for Name",
    hidden: false,
  },
  {
    key: "markForAddress1",
    label: "Mark for Address 1",
    hidden: false,
  },
  {
    key: "markForAddress2",
    label: "Mark for Address 2",
    hidden: false,
  },
  {
    key: "markForCity",
    label: "Mark for City",
    hidden: false,
  },
  {
    key: "markForState",
    label: "Mark for State",
    hidden: false,
  },
  {
    key: "markForPostal",
    label: "Mark for Postal",
    hidden: false,
  },
  {
    key: "markForCountry",
    label: "Mark for Country",
    hidden: false,
  },
  {
    key: "shippingContainerCode",
    label: "Shipping Container Code",
    hidden: false,
  },
  {
    key: "nationalDrugCode",
    label: "National Drug Code",
    hidden: false,
  },
  {
    key: "expirationDate",
    label: "Expiration Date",
    hidden: false,
  },
  {
    key: "dist",
    label: "Dist",
    hidden: false,
  },
  {
    key: "scheduledQuantity",
    label: "Scheduled Quantity",
    hidden: false,
  },
  {
    key: "scheduledQtyUom",
    label: "Scheduled Qty UOM",
    hidden: false,
  },
  {
    key: "requiredByDate",
    label: "Required By Date",
    hidden: false,
  },
  {
    key: "mustArriveBy",
    label: "Must Arrive By",
    hidden: false,
  },
  {
    key: "entireShipment",
    label: "Entire Shipment",
    hidden: false,
  },
  {
    key: "agreementNumber",
    label: "Agreement Number",
    hidden: false,
  },
  {
    key: "additionalVendorPartNumber",
    label: "Additional Vendor Part Number",
    hidden: false,
  },
  {
    key: "buyerPartNumber",
    label: "Buyer Part Number",
    hidden: false,
  },
  {
    key: "carrierDetailsSpecialHandling",
    label: "Carrier Details Special Handling",
    hidden: false,
  },
  {
    key: "releaseNumber",
    label: "Release Number",
    hidden: false,
  },
];

export type TradingPartnerNames =
  | "cvs"
  | "target"
  | "unfi"
  | "mclane"
  | "kehe"
  | "walmart"
  | "oas"
  | "core-mark"
  | "harris teeter"
  | "meijer"
  | "francesca's"
  | "wegmans"
  | "heb"
  | "crate and barrel";

